#!/usr/bin/env bash
# Removes generated/runtime artefacts, leaving source code and raw data intact.
#
# Usage:
#   ./cleansing_job.sh.sh          # dry-run (shows what would be deleted)
#   ./cleansing_job.sh --confirm   # actually delete

set -euo pipefail

DRY_RUN=true
if [[ "${1:-}" == "--confirm" ]]; then
    DRY_RUN=false
fi

# Targets
TARGETS=(
    # uv python environment
    ".venv"
    "uv.lock"
    "=2.1.0"  # uv's cache directory
    ".python-version"  # uv's marker file for the python version used in the project


    # Python bytecode caches
    "__pycache__"

    # workspace directories generated by the FL run
    # output and logs
    "data/IoV"
    "data/processed/"
    "workspace_iov_double_rf"
    "jobs/iov_double_rf_5_sites"
    "reports/"
)
# ── Run ───────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
if $DRY_RUN; then
    echo "=== DRY RUN (pass --confirm to actually delete) ==="
else
    echo "=== DELETING ==="
fi
echo ""

DELETED=0
SKIPPED=0

for target in "${TARGETS[@]}"; do
    full_path="$SCRIPT_DIR/$target"
    if [ -e "$full_path" ]; then
        if $DRY_RUN; then
            echo "  [would delete]  $target"
        else
            rm -rf "$full_path"
            echo "  [deleted]       $target"
        fi
        DELETED=$((DELETED + 1))
    else
        echo "  [not found]     $target"
        SKIPPED=$((SKIPPED + 1))
    fi
done

echo ""
if $DRY_RUN; then
    echo "Dry run complete. $DELETED item(s) would be removed ($SKIPPED not found)."
    echo "Run with --confirm to proceed: ./cleansing_this_project.sh --confirm"
else
    echo "Done. $DELETED item(s) removed ($SKIPPED not found)."
fi
echo ""
